In [1]:
import numpy as np

In [2]:
import time

In [3]:
time.time()

1680287555.6753933

In [4]:
time.time()/60/60/24/365

53.28156886389801

In [5]:
size = 10000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("Python list took: ", time.time() - start,"second")

start2 = time.time()
result2 = a1 + a2
print("numpy list took:", time.time() - start2,"second")

Python list took:  0.7301902770996094 second
numpy list took: 0.015773773193359375 second


In [6]:
a = [1,2,3,4]
b = [2,3,4,1]

result = [a[i] * b[i] for i in range(len(a))]
result

[2, 6, 12, 4]

In [7]:
a1 = np.array(a)
a2 = np.array(b)
print(a1 * a2)
print(a1 + a2)
print(a1 - a2)
print(a1 / a2)

[ 2  6 12  4]
[3 5 7 5]
[-1 -1 -1  3]
[0.5        0.66666667 0.75       4.        ]


In [32]:
import sys

l = range(1000)

print(sys.getsizeof(5))
print(sys.getsizeof(5) * 1000)


a = np.arange(1000)

print(a.itemsize)
print(a.itemsize * a.size)

28
28000
4
4000


In [9]:
mylist = [1,2,3]
np.array(mylist)


array([1, 2, 3])

In [10]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
myarray = np.array(mylist2)
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
myarray.reshape(12,) (1,12) (12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
myarray.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [14]:
myarray.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
myarray.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
myarray.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
liste = list(range(0,12))

In [18]:
liste

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [19]:
myarray2 = np.array(liste, ndmin = 5)

In [20]:
myarray2

array([[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]]]])

In [33]:
myarray2.ndim

5

In [21]:
print("Bu kadar boyut var =",myarray2.ndim)

Bu kadar boyut var = 5


In [22]:
myarray2.shape

(1, 1, 1, 1, 12)

In [23]:
my_init = np.array([1,2,3])
my_init

array([1, 2, 3])

In [24]:
my_init.dtype

dtype('int32')

In [25]:
my_float = np.array([1.,2.,3.,5,6])

In [26]:
my_float.dtype

dtype('float64')

In [27]:
my_string = np.array([1.,2.,3.,5,6,"aaaa"])

In [28]:
my_string.dtype

dtype('<U32')

In [39]:
x = np.array([1,2], dtype = np.float64)
print(x)
print(x.dtype)

[1. 2.]
float64


In [48]:
newx = x.astype("i")
print(newx)
print(newx.dtype)

[1 2]
int32


In [53]:
arr = np.array([0,1,2,None])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[False  True  True False]
bool
